version: '3'

services:
  timescaledb:
    container_name: timescaledb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PG_VERSION=14
        - PG_TAG=-bullseye
        - TS_VERSION=2.14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data/db:/var/lib/postgresql/data